require("johnil.packer")
require("johnil.nvim-treesitter")
require("johnil.settings")
require("johnil.keymaps")
require("johnil.nvim-lspconfig")
require("johnil.formatter")
-- require("johnil.nvim-lint")
require("johnil.nvim-cmp")
require("johnil.indent-blankline")
require("johnil.nvim-autopairs")
require("johnil.luasnip")
require("johnil.friendly-snippets")
